In [1]:
# testing the efficiency of numpy

%timeit
import numpy as np

# create an array with 10^7 elements
arr = np.arange(1e7)

# converting ndarray to list
larr = arr.tolist()

# List can not bydefault broadcasts therefore a function is coded to emulate what an ndarray can do
def list_times(alist,scalar):
    for i, val in enumerate(alist):
        alist[i] = val * scalar
    return alist

# using pythons magic time it command
%timeit arr * 1.1

%timeit list_times(larr, 1.1)

The slowest run took 4.39 times longer than the fastest. This could mean that an intermediate result is being cached.
10 loops, best of 3: 31.4 ms per loop
1 loop, best of 3: 1.25 s per loop


In [2]:
# linear algebra operations in numpy
import numpy as np

# creating a 3D numpy array
arr = np.zeros((3,3,3))

# trying to convert array to matrix which will not work
# TODO: remember when using the matrices in the future
try:
    mat = np.matrix(arr)
except ValueError as er:
    print er

shape too large to be a matrix.


In [3]:
# Array creation and Data Typing

alist = [1,2,3]
arr = np.array(alist)
print arr

# filling the array with zeros
arr = np.zeros(5)
print arr

# an array going from range 0 to 100
arr = np.arange(100)
print arr

# from 10 to 100
arr = np.arange(10,100)
print arr

# if want 100 steps from 1 to 100
arr = np.linspace(0,1, 100)
print arr

# or if you want to generate an array from 1 to 10
# in log 10 space in 100 steps
arr = np.logspace(0, 1, 100, base=10.0)
print arr

# Creating a 5 x 5 array of zeros (an image)
image = np.zeros((5,5))
print image

# creating a 5 x 5 x 5 cube of 1's
# the astype method sets the array with integer elements
cube = np.zeros((5,5,5)).astype(int) + 1
print cube

# or even simpler with 16 bit floating point precision
cube = np.ones((5, 5, 5)).astype(np.float16)

[1 2 3]
[ 0.  0.  0.  0.  0.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84
 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[ 0.          0.01010101  0.02020202  0.03030303  0.04040404  0.05050505
  0.06060606  0.07070707  0.08080808  0.09090909  0.1010101   0.11111111
  0.12121212  0.13131313  0.14141414  0.15151515  0.16161616  0.17171717
  0.18181818  0.19191919  0.2020202   0.21212121  0.22222222  0.23232323
  0.24242424  0.25252525  0.26262626  0.27272727  0.28282828  0.29292929
  0.3030303   0.31313131 

In [4]:
# Array with 0 integers
arr = np.zeros(2, dtype=int)
print arr

# Array with 0 floats
arr = np.zeros(2, dtype=np.float32)
print arr

[0 0]
[ 0.  0.]


In [5]:
# create an array with elements from 0 to 99
arr1d = np.arange(1000)
print arr1d

# Now reshaping the array with 10 x 10 x 10 3D array
arr3d = arr1d.reshape((10, 10, 10))
print arr3d

# The reshape command can alternatively be called this way
arr3d = np.reshape(arr1d, (10, 10, 10))
print arr3d

# Inversely, we can flatten arrays
arr4d = np.zeros((10, 10, 10, 10))
arr1d = arr4d.ravel()
print arr1d
print arr1d.shape
(1000,)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

(1000,)

In [6]:
# 2.1.2 Record Arrays
# Creating an array of zeros and defining column types
# i4: 32 bit integer , f4 32 bit float, a10 string 10 characters long
recarr = np.zeros((2,), dtype=('i4,f4,a10'))
toadd = [(1,2., 'Hello'),(2,3., 'World')]
recarr[:] = toadd
recarr

array([(1, 2.0, 'Hello'), (2, 3.0, 'World')], 
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [7]:
# Creating an array of zeros and defining column types
recarr = np.zeros((2,), dtype=('i4,f4,a10'))

# Now creating the coulmns we want to put in the recarray
col1 = np.arange(2) + 1
col2 = np.arange(2, dtype=np.float32)
col3 = ['Hello', 'World']

# Here we create a list of tuples that is identical to the previous 
# toadd list
toadd = zip(col1, col2, col3)

# Assigning values to recarr
recarr[:] = toadd

# Assigning names to each column which are now by default called
# 'f0', 'f1', and 'f2'
recarr.dtype.names = ('Integers', 'Floats', 'Strings')

# If we want to access one of the columns by its name, we can do 
# the following
print recarr('Integers')



TypeError: 'numpy.ndarray' object is not callable

In [8]:
# Indexing and slicing

alist = [[1,2], [3,4]]
alist[0][1]

2

In [9]:
# Converting the list defined above info an array
arr = np.array(alist)

# TO return the (0,1) element we use ...
arr[0,1]

2

In [10]:
# Now to access the last , we simple use...
arr[:, 1]

array([2, 4])

In [11]:
# Accessing the columns is achieved in the same way which is the
# bottom row
arr[1, :]

array([3, 4])

In [12]:
# Creating an Array
arr = np.arange(5)

# Creating the index array
index = np.where(arr > 2)
print(index)

(array([3, 4]),)


In [13]:
# creating the desired array
new_arr = arr[index]

In [14]:
new_arr = np.delete(arr, index)

index = arr > 2
print(index)

new_arr = arr[index]

[False False False  True  True]


In [15]:
# This would print the required booleans
print index

# TO inver the boolean we just need to use ~
print ~index



[False False False  True  True]
[ True  True  True False False]


In [16]:
# 2.2 Boolean Statements and NumPy Arrays

# Creating an image
img1 = np.zeros((20,20)) + 3
img1[4:-4, 4:-4] = 6
img1[7:-7, 7:-7] = 9 
print img1


print '--------------------------------------------\n\n\n'
# Let filter out all values larger than 2 and less than 6.
index1 = img1 > 2
index2 = img1 < 6
compound_index = index1 & index2

# The compound statement can alternatively be written as
compound_index = (img1 > 3) & (img1 < 7)
img2 = np.copy(img1)
img2[compound_index] = 0
print img2

print '\n\n\n --------------------------------------------------\n\n\n'

[[ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  6.  6.  6.  9.  9.  9.  9.  9.  9.  6.  6.  6.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  6.  6.  6.  9.  9.  9.  9.  9.  9.  6.  6.  6.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  6.  6.  6.  9.  9.  9.  9.  9.  9.  6.  6.  6.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  6.  6.  6.  9.  9.  9.  9.  9.  9.  6.  6.  6.  3.  3.
   3.  3.]
 [ 3.  3.  3.  3.  6.  6.  6.  9.  9.  9.  9.  9.  9.  6.  6.  6.

In [17]:
index3 = img1 == 9
index4 = (index1 & index2) | index3
img3 = np.copy(img1)
img3[index4] = 0
print img3

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  6.  6.  6.  0.  0.  0.  0.  0.  0.  6.  6.  6.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  6.  6.  6.  0.  0.  0.  0.  0.  0.  6.  6.  6.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  6.  6.  6.  0.  0.  0.  0.  0.  0.  6.  6.  6.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  6.  6.  6.  0.  0.  0.  0.  0.  0.  6.  6.  6.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  6.  6.  6.  0.  0.  0.  0.  0.  0.  6.  6.  6.

In [18]:
# operate specific element in an array
import numpy as np
import numpy.random as rand

# Creating a 100 element array with random values from a standard
# normal distribution or, in other words, a gaussian distribution.
# The sigma is 1 and the mean is 0.
a = rand.randn(100)

# Here we generate an index for filtering out undesired elements
index = a > 0.2
b = a[index]
print b

[ 0.44680775  1.18704364  0.53086409  0.61305496  0.54931669  0.98356996
  1.6700901   1.5882872   0.54012399  0.20464049  0.83586296  1.52949996
  1.1090499   0.85200559  0.31700927  1.01237647  0.21115568  0.73756748
  1.75921118  1.24903865  0.9676291   1.55140793  1.99510348  1.83944446
  1.24840156  1.37559779  0.75033281  0.92652357  0.30867946  2.07196686
  0.4068889   0.80180574  0.7919351   0.57491113  0.68119324  2.06449531
  1.14114655  1.37879129]


In [19]:
# We execute some operation on the desired elements.
b = b ** 2 - 2

print b

[-1.80036283 -0.59092739 -1.71818332 -1.62416362 -1.69825117 -1.03259013
  0.78920095  0.52265624 -1.70826608 -1.95812227 -1.30133311  0.33937013
 -0.77000832 -1.27408648 -1.89950512 -0.97509388 -1.95541328 -1.45599421
  1.09482398 -0.43990245 -1.06369393  0.40686657  1.9804379   1.3835559
 -0.44149355 -0.10773071 -1.43700067 -1.14155408 -1.90471699  2.29304667
 -1.83444143 -1.35710756 -1.3728388  -1.66947719 -1.53597577  2.26214089
 -0.69778455 -0.09893457]


In [20]:
# Then we put the modified elements back into the original array
a[index] = b
print a[index]

[-1.80036283 -0.59092739 -1.71818332 -1.62416362 -1.69825117 -1.03259013
  0.78920095  0.52265624 -1.70826608 -1.95812227 -1.30133311  0.33937013
 -0.77000832 -1.27408648 -1.89950512 -0.97509388 -1.95541328 -1.45599421
  1.09482398 -0.43990245 -1.06369393  0.40686657  1.9804379   1.3835559
 -0.44149355 -0.10773071 -1.43700067 -1.14155408 -1.90471699  2.29304667
 -1.83444143 -1.35710756 -1.3728388  -1.66947719 -1.53597577  2.26214089
 -0.69778455 -0.09893457]


In [21]:
# Read and Write

import numpy as np
arr = np.loadtxt('somefile.txt')

print arr
np.savetxt('somenewfile.txt', arr)


[  10.   20.   30.   40.   50.   60.   70.   80.   90.  100.]


In [22]:
# example.txt file looks like the following
#
# XR21 32.789 1
# XR22 33.091 2

table = np.loadtxt('example.txt', 
                  dtype={'names': ('ID', 'Result', 'Type'),
                  'formats':('S4', 'f4','i2')})


In [23]:
print table

[('XR21', 32.78900146484375, 1) ('XR22', 33.090999603271484, 2)]


In [24]:
# 2.3.2 Binary Files 
# Binary files are trickier to handle but it provides advantages such as file
# size and read/write speeds

import numpy as np
# Createing a large array
data = np.empty((1000, 1000))

# saving the data with numpy.save
np.save('test.npy', data)

# If space is an issue for large files then use `numpy.savez` instead
# It is slower than numpy.save because it compresses the binary file
np.savez('test.npz', data)

# Loading the data array
newdata = np.load('test.npy')

print newdata

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [25]:
# 2.4 Math

# AX = B
# X = A ^ -1 B
import numpy as np

# Defining the matrices
A = np.matrix([
        [3, 6, -5],
        [1, -3, 2],
        [5, -1, 4]
    ])

B = np.matrix([
        [12],
        [-2],
        [10]
    ])

# SOlving for the variables , wehre we invert A
X = A ** (-1) * B
print(X)

# check
print(A*X)

[[ 1.75]
 [ 1.75]
 [ 0.75]]
[[ 12.]
 [ -2.]
 [ 10.]]


In [26]:
# using the numpy.array class not using numpy.matrix

import numpy as np
a = np.array([
        [3, 6, -5],
        [1, -3, 2],
        [5, -1, 4]
    ])

# defining the array
b = np.array([
        [12], 
        [-2],
        [10]
    ])
# or can be defined
# b = np.array([12, -2, 10])
# solving for the variables, where we invert A
X = np.linalg.inv(a).dot(b)
print(X)

# check
print(a*X)

[[ 1.75]
 [ 1.75]
 [ 0.75]]
[[  5.25  10.5   -8.75]
 [  1.75  -5.25   3.5 ]
 [  3.75  -0.75   3.  ]]


In [27]:
# Chapter 3 Scipy

# Linear Fit f(X) = ax + b

import numpy as np
from scipy.optimize import curve_fit

# creating a function to model and create data
def func(x, a, b):
    return a*x + b


# generating clean data
x = np.linspace(0, 10, 100)
y = func(x, 1, 2)

# Adding noise to the data
yn = y + 0.9 * np.random.normal(size=len(x))

# Executing curve fit on noisy data
popt, pcov = curve_fit(func, x, yn)

# popt returns the best fit values for parameters of the given model
# (func)

print(popt)

# a * exp (-(x-μ) ^2 / 2 σ^2 ) (Gaussian Fit)
# Where a is a scalar, μ is the mean, σ is the standard deviation


# Creating a function to model and create data
def func(x, a, b, c):
    return a*np.exp(-(x-b)**2/(2*c**2))

# generate clean data
x = np.linspace(0, 10, 100)
y = func(x, 1, 5, 2)

# Adding noise to the data
yn = y + 0.2 * np.random.normal(size=len(x))

#executing curve fit on noisy data
popt, pcov = curve_fit(func, x, yn)

# popt returns the best fit values for parameters of the given model (func)
print(popt)


[ 0.97673333  2.18681751]
[ 0.94448858  5.03981135  2.2400895 ]


In [6]:
# one dimensional dataset with multiple gaussian profiles

# Two gaussian model
def func(x, a0, b0, c0, a1, b1, c1):
    return a0*np.exp(-(x-b0)**2/(2 * c0 **2)) + \
           a1*np.exp(-(x-b1)**2/(2 * c1 **2))
    
# Generating clean data
x = np.linspace(0, 20, 200)
y = func(x, 1, 3, 1, -2, 15, 0.5)

# Adding noise to the data
yn = y + 0.2 * np.random.normal(size=len(x))

# Since we are fitting a more complex function,
# providing guesses for the fitting will lean to
# better results.
guesses = [1, 3, 1, 1, 15, 1]
# Executing curve fit on noisy data
popt, pcov = curve_fit(func, x, yn, p0=guesses)

In [29]:
# Solution to Functions
from scipy.optimize import fsolve
import numpy as np

line = lambda x: x + 3

solution = fsolve(line, -2)

print solution

# finding the intersection points between two equations is nearly as 
# simple

from scipy.optimize import fsolve
import numpy as np

# Defining function to simplify intersection solution
def findIntersection(func1, func2, x0):
    return fsolve(lambda x : func1(x) - func2(x), x0)


# Defining functions that will intersect
funky = lambda x : np.cos(x/5) * np.sin(x / 2)
line = lambda x : 0.01 * x - 0.5

# Defining range and getting solutions on intersection points
x = np.linspace(0, 45, 10000)
result = findIntersection(funky, line, [15, 20, 30, 35, 40, 45])

# Printing out results for x and y
print(result, line(result))

[-3.]
(array([ 13.40773078,  18.11366128,  31.78330863,  37.0799992 ,
        39.84837786,  43.8258775 ]), array([-0.36592269, -0.31886339, -0.18216691, -0.12920001, -0.10151622,
       -0.06174122]))


In [31]:
# 3.2 Interpolation
import numpy as np
from scipy.interpolate import interp1d

# Setting up fake data
x = np.linspace(0, 10 * np.pi, 20)
y = np.cos(x)

# Interpolating data
f1 = interp1d(x, y, kind='linear')
fq = interp1d(x, y, kind='quadratic')

# x.min and x.max are used to make sure we do not
# go beyond the boundaries of the data for the 
# interpolation

xint = np.linspace(x.min(), x.max(), 1000)
yint =  f1(xint)
yintq = fq(xint)

In [32]:
# Interpolating noisy data
import numpy as np
import matplotlib.pyplot as mpl
from scipy.interpolate import UnivariateSpline

# Setting up fake data with artificial noise
sample = 30
x = np.linspace(1, 10 * np.pi, sample)
y = np.cos(x) + np.log10(x) + np.random.randn(sample) / 10

# Interpolating the data
f = UnivariateSpline(x, y, s=1)

#x.min and x.max are used to make sure we do not
# go beyond the boundaries of the data for the 
# interpolation.
xint = np.linspace(x.min(), x.max(), 1000)
yint = f(xint)



In [34]:
# multivariate data example
import numpy as np
from scipy.interpolate import griddata

# Defining a function
ripple = lambda x, y: np.sqrt(x**2 + y**2)+np.sin(x**2 + y**2)


# Generating gridded data, The complex number defines
# how many steps the grid data should have. Without the
# comples number mgrid would only create a grid data structure
# with 5 steps.
grid_x, grid_y = np.mgrid[0:5:1000j, 0:5:1000j]

# Generating sample that interpolation function will see
xy = np.random.rand(1000, 2)
sample = ripple(xy[:, 0] * 5,  xy[:, 1] * 5)

# Interpolating data with a cubic
grid_z0 = griddata(xy * 5, sample, (grid_x, grid_y), method ='cubic')

In [ ]:
# Another multivariate spline interpolation

import numpy as np
from scipy.interpolate import SmoothBivariateSpline as SBS

# Defining a function
ripple = lambda x, y: np.sqrt(x**2 + y**2)+np.sin(x**2 + y**2)

# Generating sample that interpolation function will see
xy = np.random.rand(1000, 2)
x, y xy[:,0], xy[:,1]
sample = ripple(xy[:,0] * 5, xy[:,1] * 5)

# Interpolating data
fit = SBS(x * 5, y * 5, sample, s=0.01, kx=4, ky=4)
