In [2]:
# import numpy
import numpy as np

In [3]:
# now make a matrix of 3 * 5 using numpy
array1 = np.arange(15).reshape(3,5)

In [4]:
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
array1.shape

(3, 5)

In [6]:
array1.ndim

2

In [7]:
array1.dtype.name

'int64'

In [8]:
array1.itemsize

8

In [9]:
array1.size

15

In [10]:
type(array1)

numpy.ndarray

In [11]:
array2 = np.array([6,7,8])

In [12]:
array2

array([6, 7, 8])

In [13]:
type(array2)

numpy.ndarray

In [14]:
# array of integer
int_array = np.array([[1,2,3],[4,5,6]])

In [15]:
int_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# array of float
float_array = np.array([[1.2,2.4,3.1],[4.7,5.4,6.9]])

In [17]:
float_array

array([[ 1.2,  2.4,  3.1],
       [ 4.7,  5.4,  6.9]])

In [18]:
# dynamic arrays made
dyn_array = np.array([[1.2,3,4],[5,6,8]])

In [19]:
dyn_array

array([[ 1.2,  3. ,  4. ],
       [ 5. ,  6. ,  8. ]])

In [20]:
# array of complex numbers 
complex_array = np.array([[1,2],[3,4]], dtype=complex)

In [21]:
complex_array

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [22]:
# filling zeros
zero_array = np.zeros((3,4))

# fillinf ones
ones_array = np.ones((2,3,4), dtype=np.int16)

In [23]:
zero_array

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [24]:
ones_array

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
# uninitialized output may vary
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [27]:
# take values from range 10 to 30 by difference of 5
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [28]:
# accepts float argument from range 0 to 2 with the difference of 0.3
np.arange( 0, 2, 0.3 ) 

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [31]:
# When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, 
#due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives 
# as an argument the number of elements that we want,
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2


array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [32]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)

In [33]:
print x

[ 0.          0.06346652  0.12693304  0.19039955  0.25386607  0.31733259
  0.38079911  0.44426563  0.50773215  0.57119866  0.63466518  0.6981317
  0.76159822  0.82506474  0.88853126  0.95199777  1.01546429  1.07893081
  1.14239733  1.20586385  1.26933037  1.33279688  1.3962634   1.45972992
  1.52319644  1.58666296  1.65012947  1.71359599  1.77706251  1.84052903
  1.90399555  1.96746207  2.03092858  2.0943951   2.15786162  2.22132814
  2.28479466  2.34826118  2.41172769  2.47519421  2.53866073  2.60212725
  2.66559377  2.72906028  2.7925268   2.85599332  2.91945984  2.98292636
  3.04639288  3.10985939  3.17332591  3.23679243  3.30025895  3.36372547
  3.42719199  3.4906585   3.55412502  3.61759154  3.68105806  3.74452458
  3.8079911   3.87145761  3.93492413  3.99839065  4.06185717  4.12532369
  4.1887902   4.25225672  4.31572324  4.37918976  4.44265628  4.5061228
  4.56958931  4.63305583  4.69652235  4.75998887  4.82345539  4.88692191
  4.95038842  5.01385494  5.07732146  5.14078798  5.2

In [34]:
print f

[  0.00000000e+00   6.34239197e-02   1.26592454e-01   1.89251244e-01
   2.51147987e-01   3.12033446e-01   3.71662456e-01   4.29794912e-01
   4.86196736e-01   5.40640817e-01   5.92907929e-01   6.42787610e-01
   6.90079011e-01   7.34591709e-01   7.76146464e-01   8.14575952e-01
   8.49725430e-01   8.81453363e-01   9.09631995e-01   9.34147860e-01
   9.54902241e-01   9.71811568e-01   9.84807753e-01   9.93838464e-01
   9.98867339e-01   9.99874128e-01   9.96854776e-01   9.89821442e-01
   9.78802446e-01   9.63842159e-01   9.45000819e-01   9.22354294e-01
   8.95993774e-01   8.66025404e-01   8.32569855e-01   7.95761841e-01
   7.55749574e-01   7.12694171e-01   6.66769001e-01   6.18158986e-01
   5.67059864e-01   5.13677392e-01   4.58226522e-01   4.00930535e-01
   3.42020143e-01   2.81732557e-01   2.20310533e-01   1.58001396e-01
   9.50560433e-02   3.17279335e-02  -3.17279335e-02  -9.50560433e-02
  -1.58001396e-01  -2.20310533e-01  -2.81732557e-01  -3.42020143e-01
  -4.00930535e-01  -4.58226522e-01

In [35]:
a = np.arange(6)                         # 1d array
print a

[0 1 2 3 4 5]


In [36]:
b = np.arange(12).reshape(4,3)           # 2d array
print b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [37]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print c

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
